heat_template_version: 2013-05-23

description: >
  HOT template to create a network policy for applying
  service between two VNs created before.
  Attach the network policy to two virtual networks

parameters:
  policy_name:
    type: string
    description: Virtual network id
  direction:
    type: string
    description: Direction of Policy
  start_src_ports:
    type: number
    description: Start of src port
  end_src_ports:
    type: number
    description: End of src port
  start_dst_ports:
    type: number
    description: Start of dst port
  end_dst_ports:
    type: number
    description: End of dst port
  action:
    type: string
    description: service to apply
  private_net_1_name:
    type: string
    description: Name of private network to be created
  private_net_2_name:
    type: string
    description: Name of private network to be created

resources:
  private_policy:
    type: OS::Contrail::NetworkPolicy
    properties:
      name: { get_param: policy_name }
      entries:
        policy_rule: [
              { 
                "direction": { get_param: direction }, 
                "protocol": "any", 
                "src_ports": [{"start_port": {get_param: start_src_ports}, "end_port": {get_param: end_src_ports}}],
                "dst_ports": [{"start_port": {get_param: start_dst_ports}, "end_port": {get_param: end_dst_ports}}],
                "dst_addresses": [{ "virtual_network": {get_param: private_net_1_name}}], 
                "action_list": {"simple_action": {get_param: action}}, 
                "src_addresses": [{ "virtual_network": {get_param: private_net_2_name}}] 
              }, 
        ]
  private_policy_attach_net1:
    type: OS::Contrail::AttachPolicy
    properties:
      network: { get_param: private_net_1_name }
      policy: { get_attr: [private_policy, fq_name] }

  private_policy_attach_net2:
    type: OS::Contrail::AttachPolicy
    properties:
      network: { get_param: private_net_2_name }
      policy: { get_attr: [private_policy, fq_name] }
